apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: jailbot
  annotations: {}
spec:
  rules:
  - host: jailbot.bluetrack.io
    http:
      paths:
      - path: /
        backend:
          serviceName: jailbot
          servicePort: http
  tls:
  - hosts: ["jailbot.bluetrack.io"]
    secretName: jailbot-tls
